In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
torch.__version__

'1.12.1+cu113'

# Introduction to tensor

In [2]:
scalar  = torch.tensor(7)
scalar

tensor(7)

In [3]:
# number of dimension
scalar.ndim

0

In [4]:
# get the data from the tensor
scalar.item()

7

In [5]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
matrix = torch.tensor([[7,7],
                       [3,5]])
matrix

tensor([[7, 7],
        [3, 5]])

In [9]:
matrix.ndim

2

In [10]:
matrix.shape

torch.Size([2, 2])

In [11]:
matrix[np.s_[0]]

tensor([7, 7])

In [12]:
# tensor
tensor = torch.tensor([[[1,2,4],
                        [124,235,3],
                        [123,32,34]]])
tensor

tensor([[[  1,   2,   4],
         [124, 235,   3],
         [123,  32,  34]]])

In [13]:
tensor.shape,tensor.ndim

(torch.Size([1, 3, 3]), 3)

In [14]:
tensor[0]

tensor([[  1,   2,   4],
        [124, 235,   3],
        [123,  32,  34]])

In [15]:
tensor[0,0]

tensor([1, 2, 4])

# Random tensor

In [16]:
# create a random tensor of shape (4,3)
random_tensor = torch.rand(4,3)
random_tensor

tensor([[0.0880, 0.3197, 0.3824],
        [0.5949, 0.1374, 0.1600],
        [0.5455, 0.8716, 0.8542],
        [0.2833, 0.3546, 0.2824]])

In [17]:
help(torch.rand)

Help on built-in function rand in module torch:

rand(...)
    rand(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor
    
    Returns a tensor filled with random numbers from a uniform distribution
    on the interval :math:`[0, 1)`
    
    The shape of the tensor is defined by the variable argument :attr:`size`.
    
    Args:
        size (int...): a sequence of integers defining the shape of the output tensor.
            Can be a variable number of arguments or a collection like a list or tuple.
    
    Keyword args:
        generator (:class:`torch.Generator`, optional): a pseudorandom number generator for sampling
        out (Tensor, optional): the output tensor.
        dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
            Default: if ``None``, uses a global default (see :func:`torch.set_default_tensor_type`).
        layout (:class:`torch.layout`, optional): the desired layout of returne

In [18]:
# create a random tensor with similar to shape to image tensor
random_image_size_tensor = torch.rand(size=(3,10,10))
random_image_size_tensor.shape,random_image_size_tensor.size()

(torch.Size([3, 10, 10]), torch.Size([3, 10, 10]))

# Zeros and ones

In [19]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

# Range

In [22]:
one_to_ten = torch.arange(start=0,end=10,step=1)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
one_to_ten.shape

torch.Size([10])

# Tensor like

In [24]:
help(torch.zeros_like)

Help on built-in function zeros_like in module torch:

zeros_like(...)
    zeros_like(input, *, dtype=None, layout=None, device=None, requires_grad=False, memory_format=torch.preserve_format) -> Tensor
    
    Returns a tensor filled with the scalar value `0`, with the same size as
    :attr:`input`. ``torch.zeros_like(input)`` is equivalent to
    ``torch.zeros(input.size(), dtype=input.dtype, layout=input.layout, device=input.device)``.
    
    .. warning::
        As of 0.4, this function does not support an :attr:`out` keyword. As an alternative,
        the old ``torch.zeros_like(input, out=output)`` is equivalent to
        ``torch.zeros(input.size(), out=output)``.
    
    Args:
        input (Tensor): the size of :attr:`input` will determine size of the output tensor.
    
    Keyword args:
        dtype (:class:`torch.dtype`, optional): the desired data type of returned Tensor.
            Default: if ``None``, defaults to the dtype of :attr:`input`.
        layout (:class:

In [25]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor data type

In [26]:
float_32_tensor = torch.tensor([3,3,3],dtype=torch.float32,
                               device=None,
                               requires_grad=False)
float_32_tensor.dtype

torch.float32

In [27]:
float_32_tensor.device

device(type='cpu')

In [28]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor , float_16_tensor.dtype

(tensor([3., 3., 3.], dtype=torch.float16), torch.float16)

In [29]:
float_16_tensor * float_32_tensor

tensor([9., 9., 9.])

# Getting information from tensor

In [30]:
# to get the dtype
float_32_tensor.dtype

torch.float32

In [31]:
# get the device
float_32_tensor.device

device(type='cpu')

In [32]:
# shape
print(float_32_tensor.shape )
print(float_32_tensor.size())
print(torch.Tensor.size(float_32_tensor))

torch.Size([3])
torch.Size([3])
torch.Size([3])


In [33]:
# get the data item
float_32_tensor.data

tensor([3., 3., 3.])

# Manipulating Tensor

In [34]:
tensor = torch.tensor([1,2,3])
print(tensor + 10)

tensor([11, 12, 13])


In [35]:
%%timeit -n 5000 -r 50
tensor + 10

2.98 µs ± 53.7 ns per loop (mean ± std. dev. of 50 runs, 5000 loops each)


In [36]:
%%timeit -n 5000 -r 50
tensor.add(10)

3.09 µs ± 75.6 ns per loop (mean ± std. dev. of 50 runs, 5000 loops each)


In [37]:
%%timeit -n 5000 -r 50
tensor * 10

3.07 µs ± 574 ns per loop (mean ± std. dev. of 50 runs, 5000 loops each)


In [38]:
%%timeit -n 5000 -r 50
tensor.mul(10)

2.99 µs ± 45 ns per loop (mean ± std. dev. of 50 runs, 5000 loops each)


# Matrix Multiplication

In [39]:
torch.matmul(tensor,tensor)

tensor(14)

In [40]:
%%timeit -n 5000 -r 50
torch.matmul(tensor,tensor)

1.98 µs ± 70 ns per loop (mean ± std. dev. of 50 runs, 5000 loops each)


In [41]:
result = 0
for i in tensor:
    result += i**2
result

tensor(14)

In [42]:
%%timeit -n 5000 -r 50
result = 0
for i in tensor:
    result += i**2

21.1 µs ± 1.31 µs per loop (mean ± std. dev. of 50 runs, 5000 loops each)


In [43]:
%%timeit -n 5000 -r 50
torch.rand(size=(4,3)).matmul(torch.rand(3,4))

8.83 µs ± 562 ns per loop (mean ± std. dev. of 50 runs, 5000 loops each)


In [44]:
%%timeit -n 5000 -r 50
torch.rand(size=(4,3)) @ (torch.rand(3,4))

9.65 µs ± 1.76 µs per loop (mean ± std. dev. of 50 runs, 5000 loops each)


In [45]:
%%timeit -n 5000 -r 50
# mm is alias for matmul
torch.rand(size=(4,3)).mm(torch.rand(3,4))

9.57 µs ± 1.74 µs per loop (mean ± std. dev. of 50 runs, 5000 loops each)


# Reshape and Transpose

In [46]:
tensor_a = torch.rand(size=(4,3))
tensor_b = torch.rand(size=(4,3))

In [47]:
try:
    tensor_a.matmul(tensor_b)
except RuntimeError as err:
    print(err)

mat1 and mat2 shapes cannot be multiplied (4x3 and 4x3)


In [48]:
%%timeit -n 5000 -r 50
tensor_a.reshape(3,4)

1.56 µs ± 81.3 ns per loop (mean ± std. dev. of 50 runs, 5000 loops each)


In [49]:
%%timeit -n 5000 -r 50
tensor_a.reshape(3,4).matmul(tensor_b)

4.89 µs ± 642 ns per loop (mean ± std. dev. of 50 runs, 5000 loops each)


In [50]:
%%timeit -n 5000 -r 50
tensor_a.T

1.24 µs ± 66.1 ns per loop (mean ± std. dev. of 50 runs, 5000 loops each)


In [51]:
%%timeit -n 5000 -r 50
tensor_a.T.matmul(tensor_b)

4.6 µs ± 632 ns per loop (mean ± std. dev. of 50 runs, 5000 loops each)


# Tensor Aggregation

In [52]:
# mean
x = torch.arange(1,10)
x,x.dtype

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.int64)

arange default data type is `int64`

In [53]:
%%timeit -n 5000 -r 50
x.min()

1.59 µs ± 143 ns per loop (mean ± std. dev. of 50 runs, 5000 loops each)


In [54]:
%%timeit -n 5000 -r 50
x.max()

1.53 µs ± 65.5 ns per loop (mean ± std. dev. of 50 runs, 5000 loops each)


1. mean can only work with the float and complex
2. Cant not work with int


In [55]:
try:
    x.mean()
except RuntimeError as err:
    print(err)

mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long


In [56]:
%%timeit -n 5000 -r 50
x.type(torch.float32).mean()

9.13 µs ± 568 ns per loop (mean ± std. dev. of 50 runs, 5000 loops each)


# Finding the positional min and max


In [57]:
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
x.argmax()

tensor(8)

In [59]:
x.argmin()

tensor(0)

# where

In [60]:
# you can get the index of the value
torch.where(x==5)[0].item()

4

In [61]:
torch.where(x>3,x,0)

tensor([0, 0, 0, 4, 5, 6, 7, 8, 9])

# Reshaping ,stacking ,squeezing and un squeeze

In [62]:
x = torch.arange(1.,10.)
x ,x.shape,x.dtype,x.ndim

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]),
 torch.float32,
 1)

In [63]:
# add extra dimension
x_reshaped = x.reshape((1,-1))
x_reshaped,x_reshaped.shape,x_reshaped.ndim

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]), 2)

## View

In [64]:
# Using the view is same as the reshape but inplace
z = x.view(3,3)
z

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [65]:
z[:,0] = 100
z

tensor([[100.,   2.,   3.],
        [100.,   5.,   6.],
        [100.,   8.,   9.]])

In [66]:
x

tensor([100.,   2.,   3., 100.,   5.,   6., 100.,   8.,   9.])

In [67]:
# address of tensor is different
id(z) == id(x)

False

In [68]:
# but the element will have same memory address
id (x[0]) == id(z[0])

True

## Stack

In [95]:
x = torch.arange(1.0,10.,1.)
x ,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [96]:
torch.stack([x,x],dim=0)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [97]:
torch.row_stack([x,x])

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [98]:
torch.vstack([x,x])

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [99]:
torch.stack([x,x],dim=1)

tensor([[1., 1.],
        [2., 2.],
        [3., 3.],
        [4., 4.],
        [5., 5.],
        [6., 6.],
        [7., 7.],
        [8., 8.],
        [9., 9.]])

In [100]:
torch.column_stack([x,x])

tensor([[1., 1.],
        [2., 2.],
        [3., 3.],
        [4., 4.],
        [5., 5.],
        [6., 6.],
        [7., 7.],
        [8., 8.],
        [9., 9.]])

hstack is equal to the column stack but 1d tensor it concat , to perform the column stack we need to reshape it 2d tensor

In [101]:
torch.hstack([x,x])

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [102]:
z = x.reshape(-1,1)
torch.hstack([z,z])

tensor([[1., 1.],
        [2., 2.],
        [3., 3.],
        [4., 4.],
        [5., 5.],
        [6., 6.],
        [7., 7.],
        [8., 8.],
        [9., 9.]])

## Squeeze and Un squeeze

Squeeze  --> remove the all the single dimension
unsqueeze --> add the single dimension to specified dimension


In [103]:
z.shape

torch.Size([9, 1])

In [104]:
z.squeeze().shape

torch.Size([9])

In [105]:
x.shape

torch.Size([9])

In [106]:
help(x.unsqueeze)

Help on built-in function unsqueeze:

unsqueeze(...) method of torch.Tensor instance
    unsqueeze(dim) -> Tensor
    
    See :func:`torch.unsqueeze`



In [107]:
x.unsqueeze(dim=1).shape

torch.Size([9, 1])

In [108]:
x.unsqueeze(dim=0).shape

torch.Size([1, 9])

## Permute

`Return the view of the tensor` **Not the copy**

In [112]:
help(torch.Tensor.permute)

Help on method_descriptor:

permute(...)
    permute(*dims) -> Tensor
    
    See :func:`torch.permute`



In [109]:
x_image = torch.rand(size=(224,224,3)) # [height,width,color_channel]
x_image.shape

torch.Size([224, 224, 3])

In [111]:
# change the color channel to first index
x_permuted = x_image.permute(2,0,1)  # [color_channel,height,width]
x_permuted.shape

torch.Size([3, 224, 224])

In [118]:
# both having the same value
x_image[66,77,2] ,x_permuted[2,66,77]

(tensor(0.6708), tensor(0.6708))

In [120]:
# let change the value in the permuted tensor
x_permuted[2,66,77] = 1000

In [121]:
# since element of the both tensor are same  ie is view
x_image[66,77,2] ,x_permuted[2,66,77]

(tensor(1000.), tensor(1000.))

## Transpose

This is also return the view

In [124]:
x_transpose = x_image.T
x_transpose.shape

torch.Size([3, 224, 224])

In [126]:
x_image[66,77,2] ,x_transpose[2,77,66]

(tensor(1000.), tensor(1000.))

In [127]:
x_transpose[2,77,66] = 2000

In [128]:
x_image[66,77,2] ,x_transpose[2,77,66]

(tensor(2000.), tensor(2000.))

## Stride

array is continuous memory , stride specify the jump in the continuous memory to get the element in that dimension

In [141]:
x_stride = torch.rand(2,3)
x_stride

tensor([[0.3882, 0.2310, 0.2949],
        [0.1299, 0.7173, 0.4240]])

In [143]:
x_stride.shape ,x_stride.stride()

(torch.Size([2, 3]), (3, 1))

stride is (3,1) it says
for dimension zero, i have to jump three element to pick the next element
for dimension one, i have to jump one element to pick the next element


In [144]:
x_stride.flatten()

tensor([0.3882, 0.2310, 0.2949, 0.1299, 0.7173, 0.4240])

In [138]:
x_image.shape, x_image.stride()

(torch.Size([224, 224, 3]), (672, 3, 1))

In [139]:
x_transpose.shape,x_transpose.stride()

(torch.Size([3, 224, 224]), (1, 3, 672))

# Pytorch and Numpy

* Numpy --> Pytorch : `torch.from_numpy(ndarray)`
* Pytorch --> Numpy : `torch.Tensor.numpy()`

In [148]:
# from numpy to tensor
import numpy as np

array = np.arange(1.,11.)
tensor = torch.tensor(array)
array,tensor

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64))

numpy default is float64.
torch default is float32.

when we convert the numpy to torch , it perseveres the data type

In [149]:
# tensor to numpy
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64),
 array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

# Reproducibility

In [158]:
torch.manual_seed(42)
torch.rand(4,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

In [159]:
torch.manual_seed(42)
torch.rand(4,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

# Running tensor on GPUs

In [2]:
import torch
torch.cuda.is_available()

False